CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6 ~/anaconda3/envs/taizhou/bin/python main.py \
-train \
--dataset Data/DataInPatientsUmap \
--model Transformer \
--optimizer Lion \
--max_length 10000 \
--lr 2e-6 \
--warmup_steps 10 \
--warmup_start_lr 1e-8 \
--power 0.5 \
--batchsize 200 \
--length 1000 \
--epochs 500 \
--device cuda \
--nonlin elu \
--save_dir ./Results/UMAP_Results \
--weight_decay 0.1 \
--dropout_rate 0.5 \
--input_droprate 0. \
--test_model_path Results/DNN-notShuffle-dropout0d5/DNN_Adam_98.23_checkpoint.t7 \
-deterministic